In [1]:
import os
import cv2
import glob
import numpy as np
t=[]
y_test=[]
l=[]
y_train=[]
ma=0
labels=[1,2,3,4,5,6,7,8]

def ellipse_variance(contour):
    M=cv2.moments(contour)
    cX=int(M['m10']/M['m00'])
    cY=int(M['m01']/M['m00'])
    v=np.zeros((1,2,1))
    for cord in contour:
        x=np.array([[[cord[0][0]-cX],[cord[0][1]-cY]]])
        v=np.vstack((v,x))
#         print(v)
        # print(x)
#         print(cord)
#         print(cord[0][0])
#     print(v.shape)
    c_ellipse=np.zeros((2,2))
    for i in v:
        c_ellipse+=np.dot(i,np.transpose(i))
    c_ellipse/=contour.shape[0]
#     print(c_ellipse)
    c_ellipse_inv=np.linalg.inv(c_ellipse)
    d=np.zeros((1,1))
    for i in v:
        d=np.vstack((d,np.sqrt(np.dot(np.dot(np.transpose(i),c_ellipse_inv),i))))
    d=d[1:]
    mu=1/contour.shape[0]*np.sum(d)
    sigma=np.sqrt(1/contour.shape[0]*np.sum(np.square(d-mu)))
    return mu/sigma
count=0
#data=np.zeros((1,7))
for label in labels:
    count+=1
    path = "dt/"+str(label)+"/"
    cou=0
    for filename in os.listdir(path):
        cou+=1
        #print(filename,'1')
        input_path = os.path.join(path, filename)
        img=cv2.imread(input_path,0)
        ret,thresh=cv2.threshold(img,10,255,cv2.THRESH_BINARY)
        im2,contours,hierarchy=cv2.findContours(img,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
        # print(len(contours))
#         for cnt in contours:
#             a = cv2.contourArea(cnt)
#             if a>ma:
#                 c=cnt;
        req=max(contours,key=cv2.contourArea)
        # print(req.shape)
        #req=req[0]
        #req=c
        area=cv2.contourArea(req)
        #eccentricity
        dim_rect=cv2.minAreaRect(req)[1]
        para1=dim_rect[1]/dim_rect[0]
        #circularity
        perimeter=cv2.arcLength(req,True)
        para2=4*np.pi*area/(perimeter**2)
        #rectangularity
        para3=area/(dim_rect[1]*dim_rect[0])
        #convexity
        hull=cv2.convexHull(req)
        para4=cv2.arcLength(hull,True)/perimeter
        #solidity
        para5=area/cv2.contourArea(hull)
        #ellipse variance
        para6=ellipse_variance(req)
        #np.vstack((data,np.array([para1,para2,para3,para4,para5,para6,ord(label)])))
        g=[para1,para2,para3,para4,para5,para6]
        l.append(g)
        y_train.append(count)
        
#data=data[1:]
#np.save(base_dir+'/'+'data.npy',)

In [58]:
import csv
with open("testhand2.csv", "w") as f:
    writer = csv.writer(f)
    writer.writerows(t)

In [59]:
y=[]
for i in y_test:
    y.append([i])

In [60]:
import csv

with open("test_label_hand1.csv", "w") as f:
    writer = csv.writer(f)
    writer.writerows(y)

In [2]:
import csv
with open("trainhand2.csv", "w") as f:
    writer = csv.writer(f)
    writer.writerows(l)

In [3]:
y=[]
for i in y_train:
    y.append([i])

In [4]:
import csv

with open("train_label_hand2.csv", "w") as f:
    writer = csv.writer(f)
    writer.writerows(y)

In [8]:
cv2.imshow("fekbkj",thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [50]:
print(area)
print(req)

1695.5
[[[ 5 14]]

 [[ 4 15]]

 [[ 4 19]]

 [[ 5 20]]

 [[ 4 21]]

 [[ 4 24]]

 [[ 3 25]]

 [[ 3 29]]

 [[ 4 30]]

 [[ 4 32]]

 [[ 5 33]]

 [[ 5 38]]

 [[ 6 39]]

 [[ 6 42]]

 [[ 7 43]]

 [[ 7 44]]

 [[ 9 46]]

 [[10 46]]

 [[16 52]]

 [[16 53]]

 [[18 55]]

 [[19 55]]

 [[20 56]]

 [[21 56]]

 [[22 57]]

 [[23 57]]

 [[24 58]]

 [[24 59]]

 [[25 60]]

 [[25 63]]

 [[48 63]]

 [[47 62]]

 [[47 56]]

 [[48 55]]

 [[48 39]]

 [[49 38]]

 [[49 28]]

 [[48 27]]

 [[48 24]]

 [[47 23]]

 [[46 23]]

 [[45 22]]

 [[44 22]]

 [[43 21]]

 [[41 21]]

 [[40 20]]

 [[38 20]]

 [[37 19]]

 [[36 19]]

 [[35 18]]

 [[31 18]]

 [[30 19]]

 [[29 19]]

 [[27 17]]

 [[20 17]]

 [[18 19]]

 [[12 19]]

 [[10 17]]

 [[10 16]]

 [[ 9 15]]

 [[ 8 15]]

 [[ 7 14]]]


In [ ]:
print()